apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: demo
spec:
  eventBusName: codefresh-eventbus
  dependencies:
    - name: git-push
      eventSourceName: github
      eventName: push
    - name: git-push-2
      eventSourceName: github-another
      eventName: push
  triggers:
    - template:
        name: trigger-1
        conditions: git-push
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                name: submit
              spec:
                workflowTemplateRef:
                  name: whalesay
    - template:
        name: trigger-2
        conditions: git-push-2
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                name: submit
              spec:
                workflowTemplateRef:
                  name: whalesay
    - template:
        name: trigger-3
        conditions: git-push-2
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                name: submit
              spec:
                workflowTemplateRef:
                  name: whalesay
    - template:
        name: trigger-4
        conditions: git-push-2
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                name: submit
              spec:
                workflowTemplateRef:
                  name: whalesay
    - template:
        name: trigger-5
        conditions: git-push-2
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                name: submit
              spec:
                workflowTemplateRef:
                  name: whalesay
