apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test1
spec:
  entrypoint: echo
  templates:
  - name: echo
    container:
      image: alpine
      command:
        - echo
        - "test"


